icecube/pisa

- pisa/core/binning.py
- pisa/core/events_pi.py
- pisa/core/pi_stage.py
- pisa/stages/data/toy_event_generator.py
- pisa/stages/reco/simple_param.py
First batch of changes to merge following the PISA repo move. These are changes that were made during the wait for the move.
Also one fix required to the current master branch is implemented (pint version issue).
Changes are pretty uncontroversial, e.g. a few minor fixes. Some major changes to the simple parameterised reco stage (used for Upgrade work). Is more general now, and more steerable from the cfg file. Docs updated accordingly.
> Merging after PISA repo moved to IceCubeOpenSource

- pisa/core/binning.py
- pisa/core/events_pi.py
- pisa/core/pi_stage.py
- pisa/stages/data/toy_event_generator.py
- pisa/stages/reco/simple_param.py
Will implement the new hyperplane system in this branch. 
Creating a PR now to ease visibility for others during the process. Not yet requesting a merge.
> New hyperplane implementation

- pisa/stages/background/atm_muons.py
- pisa_examples/resources/settings/osc/nufitv40.cfg
- Added NuFit v4.0 osc params (cfg file)
- Fix to atmospheric muon stage, not uses a consistent method to get the correct arrays from the input data
> Some minor additions/fixes to master

- pisa/utils/hypersurface.py
Further fixes and enhancements to hypersurfaces. I re-formulated the exponential function so that it is actually numerically stable to use as there is no longer a degeneracy with the intercept. This makes it probably a better option now than the log-mode. 
Also, one less parameter means one more degree of freedom and it seems our DOM efficiency dependency in muons is very well modeled by the single-parameter version without scaling in y direction. 
The scaled version is now separate.
> Hypersurface fix + enhancement

- pisa/__init__.py
- pisa/core/pipeline.py
- pisa/stages/osc/nsi_params.py
- pisa/utils/comparisons.py
- pisa/utils/config_parser.py
- pisa_tests/run_unit_tests.py
See commit messages for description of modifications
> Fix nsi unit tests, add CTYPE, misc

- pisa/stages/flux/pi_mceq_barr_red.py
Just noticed that some of the language in the documentation is wrong since its copied from the other stage (i.e. there are not as many parameters as it claims). I also need to update the spline generation scripts which I'll do in a separate PR so I can clean up the comments in that commit tomorrow.
> checked out pi_mceq_barr_red stage from tmp branch

- pisa/core/map.py
Fix for #492 (also in #587, but I figured this better be fixed before it trips us up)
> use random state for gaussian random variates also

- pisa/core/binning.py
* Add `OneDimBinning.weighted_bin_widths`, `MultiDimBinning.weighted_bin_volumes`
* Allow `meshgrid` method of `MultiDimBinning` to accept the name of any attribute, allow failure
* Bugfix: invalidate cached items if is_{log,lin} changes
As of now, this is largely untested. I'll let @atrettin start playing with it (maybe you can even add a unit test or two?) and then we can merge this PR and create subsequent PR's to add more features to help the rebinning effort (if this is useful already), or I'll add commits to this PR with the other features requested as I develop them. (Let me know what's preferable.)
Note this PR addresses point (2) of Issue #619 (Binning enhancement to facilitate resampling), ultimately in support of PR #621 (Facilitate upsampling of weighted histograms)
> Add weighted_bin_{widths,volumes}; bugfix

- pisa/core/param.py
Implementing `collections.abc.MutableSequence` just needed addition of `insert` method. Now subclass from that to get the mix-in methods, too. (See https://docs.python.org/3/library/collections.abc.html)
Currently only a subset of the methods of Python `set` are implemented, but `collections.abc.Set` interface requirements are met. Implemented are `issubset`, `issuperset`, `isdisjoint`, `<`, `<=`, `>`, `>=` operators all function and have unit tests added. For `set`-like behavior, I think just need to add `union`, `|`, `intersection`, `&`, `difference`, `-`, `symmetric_difference`, `^`, and `copy`.
Also augmented existing unit tests, and added new tests for the above methods.
> Make pramset MutableSequence and Set

- pisa/analysis/analysis.py
This PR facilitates the blind fit procedure we are planning to follow (at least for the verification sample). When the `blind` flag evaluates to `True`, fit parameters are prevented from being printed to the console or showing up in logs, but the fitted parameters are still stored in the output dictionary. If an int > 1 is passed to `blind`, the parameters are also prevented from being stored in the output. That means `blind == 2` behaves as the previous implementation while `blind == 1` or `blind == True` is a little more relaxed. The way the fridge scripts are currently set up, the final fit results are stored in compressed JSON files that are not human readable to maintain blindness, but scripts can use them to produce post-fit data/MC comparison plots.
This PR also fixes a bug where …
> introduce two blindness levels, fix bug in highest blindness level

- pisa/stages/flux/mceq_barr_red.py
When running the stage, it always produced a numba performance warning saying that the implementation with `np.dot` inside a JIT compiled function is sub-optimal. I implemented the calculation with for-loops instead of `np.dot` and found the computation time for the oscNext high-stats sample drop from 3.7 s to 1.5 s when working in events mode. This is a decent little speed boost for oscillation fits and makes the code easier to understand as well.
> implement mceq systematic with loops

- pisa/core/param.py
- pisa/stages/data/freedom_hdf5_loader.py
new data loader for FreeDOM reco hdf5 files
> FreeDOM reader

- pisa/analysis/analysis.py
Fixed non-list metrics issue and included functions in stats.py to better condense some lines of code.
> Analysis fix

- pisa/stages/utils/kde.py
This is a bug-fix for binnings that are both logarithmic and irregular, such as the energy binning of the Verification Sample. In that case, we add a new binning that is linear and irregular in log-space and calculate the KDE in log-space as well.
> Correctly treat irregular logarithmic binning in KDE

- pisa/stages/utils/kde.py
- pisa_tests/test_kde_stage.py
The behavior of the KDE changed recently such that the KDE is applied to the logarithm of quantities that are binned logarithmically. While this is usually a good idea, this should still be configurable to recover the previous behavior if desired. The default is `True`, so that this PR should not interrupt anything currently working with the KDE stage.
> Make KDE linearization configurable

- .github/workflows/pythonpackage.yml
Changes the version of Python to be used for GitHub worflows.
> Fix python version in workflow

- pisa/utils/stats.py
Tniy bug on conv_llh was solved and updated to return bin wise conv_llh values.
> bug fix on conv_llh

- pisa/core/map.py
Fixed plot saving functionality for 3D maps and correct return types. Also added default dpi value and related argument. Started listing/implementing unit test for plot function, but not sure how necessary this is?!
> Fix 3d map plotting - saving and return values.

- pisa/core/map.py
Closes  #664 (if that was even still an issue).
> Copy+modify cmaps instead of modifying the globally registered.

- pisa/stages/aeff/aeff_hnl.py
- pisa/stages/aeff/weight_hnl.py
Add custom effective area stage for OscNext HNL analysis. Can be used to re-weight single mass HNL sets for any mixing.
Uses constants (lightspeed, planck), can they be pulled from somewhere in PISA?
> Add HNL custom effective area stage - working state.

- pisa/stages/discr_sys/README.md
- pisa/stages/discr_sys/ultrasurfaces.py
- setup.py
Add discrete systematic stage to apply ultrasurfaces. The code to predict/fit them is still in the fridge, but could potentially also be made part of pisa at some point.
> Add ultrasurface stage and edit README accordingly.

- pisa/stages/data/freedom_hdf5_loader.py
- pisa/stages/utils/kfold.py
- pisa/utils/comparisons.py
- pisa/utils/format.py
- pisa/utils/hdf.py
- pisa/utils/jsons.py
> Get rid of deprecated numpy members.

- pisa/stages/aeff/weight_hnl.py
Bugfix in HNL weighting + more comments.
> Fix Etot bug and add comments for clarity.

- pisa/utils/stats.py
Changed the output shape of mod_chi2() function to match the input shape (shape of the map).
> Re-shaped the mod_chi2's return to match the input shape

- pisa/stages/utils/fix_error.py
Clarified the use of this stage.
Followup from this discussion: https://github.com/icecube/pisa/pull/774
> Update fix_error.py description

- pisa/core/stage.py
* probably a copy-paste error (see `report_profile` in https://github.com/icecube/pisa/blob/master/pisa/core/pipeline.py#L143)
* several useless import statements removed
> Fix doubly defined `report_profile` method in `stage.py` + minor touch-ups

- pisa/stages/discr_sys/ultrasurfaces.py
> Allow for ultrasurfaces fit results file path relative to pisa resources search paths

- pisa/utils/fileio.py
> make `to_file` accept simple file name again

- .github/workflows/pythonpackage.yml
Trying to fix the python setup for the test workflows.
> Fix python test environment setup.

- pisa/utils/flavInt.py
See https://github.com/PyCQA/flake8/pull/1974
The alternative would have been to disable the check.
> Remove global statements to fix new flake8 f824 error
