pisa/utils/llh_client.py, pisa/utils/llh_server.py
This is tailored to the EMCEE tool, but the method of parallelizing getting LLH's from PISA distribution makers in parallel could benefit other use cases.
=> rough-out of llh client/server using TCP IPC for EMCEE parallelization

pisa/stages/pid/pi_shift_scale_pid.py
Added a stage that can be used to shift pid values by a bias value or scale them with a factor. This can be used to modify the pid cut value used in an analysis without having to change the binning config file.
=> Added stage to shift and/or scale pid (checked out from personal oscnext_santa branch)

pisa/core/map.py, pisa/utils/likelihood_functions.py, pisa/utils/stats.py
SAY LLH and Thorsten LLH added (check `likelihood_functions.py` for reference to the respective papers). The Barlow LLH which was implemented doesn't work since it was old code ported from oscFit. So I rewrote it in `likelihood_functions.py`. `barlow.py` is now unnecessary.
=> Added new LLH methods and reworked the Barlow LLH

pisa/analysis/nutau_analysis.py, pisa/core/binning.py, pisa/core/container.py, pisa/core/map.py, pisa/core/param.py, pisa/core/prior.py, pisa/core/translation.py, pisa/utils/cache.py, pisa/utils/comparisons.py, pisa/utils/config_parser.py, pisa/utils/fileio.py, pisa/utils/flavInt.py, pisa/utils/flavor_interaction_types.md, pisa/utils/hash.py, pisa/utils/hdf.py, pisa/utils/jsons.py, pisa/utils/llh_server.py, pisa/utils/parallel.py, pisa/utils/vbwkde.py, pisa_examples/resources/settings/pipeline/example.cfg, pisa_tests/test_command_lines.sh, pisa_tests/test_example_pipelines.py, setup.py
Should fix issue #543 , issue #551 , and other things
* allow `recursiveEquality` function to handle comparing non-float numpy arrays
* json write / read handles integer types
* improved unit testing function in `jsons.py`: `test_to_json_from_json`
* expose all constants, functions, and classes in `jsons.py`
* more python 3 compatibility fixes
* lots of stuff; see commit messages
=> Fix #543: integers/arrays thereof: to/from json, comparisons

pisa/core/container.py
This should fix issues with how dict.keys() works in Python 3.
=> Fix iteration of container dictionaries after Py3 switch.

INSTALL.md, docs/source/pisa.analysis.rst, docs/source/pisa.core.rst, docs/source/pisa.scripts.rst, docs/source/pisa.stages.absorption.rst, docs/source/pisa.stages.aeff.rst, docs/source/pisa.stages.background.rst, docs/source/pisa.stages.combine.rst, docs/source/pisa.stages.data.rst, docs/source/pisa.stages.discr_sys.rst, docs/source/pisa.stages.flux.rst, docs/source/pisa.stages.osc.nusquids.rst, docs/source/pisa.stages.osc.prob3numba.rst, docs/source/pisa.stages.osc.rst, docs/source/pisa.stages.pid.rst, docs/source/pisa.stages.reco.rst, docs/source/pisa.stages.rst, docs/source/pisa.stages.unfold.rst, docs/source/pisa.stages.utils.rst, docs/source/pisa.stages.xsec.rst, docs/source/pisa.utils.rst, pisa/scripts/convert_config_format.py, pisa/stages/GLOBALS.md, pisa/utils/config_parser.py, pisa_examples/resources/settings/discr_sys/example_discr_sys.cfg, pisa_examples/resources/settings/pipeline/example.cfg, pisa_tests/test_command_lines.sh, pisa_tests/test_hypo_testing.sh, setup.py
* bugfix: Tom changed naming conventions in some places but not everywhere, breaking example config and making docs out of date
* `pi_simple` -> `pi_barr_simple`
* `nominal_nu_flux` -> `nu_flux_nominal`, `nominal_nubar_flux` -> `nubar_flux_nominal`
* split hypo testing part of `test_command_lines.sh` into separate bash script that is individually callable to make testing just that piece easier / faster -> `test_hypo_testing.sh`
* document pisa config file param interpolation syntax; remove py2 `backports.configparser` dependency
* update dependencies listed in `INSTALL.md` & dependencies in `setup.py` to remove `backports.configparser`; add `iminuit` to dependency docs (not required for PISA to run, though, so only added to `INSTALL.md` not to `setup.py`)
* update built HTML docs
=> Fixes for Tom's naming convention changes, remove py2 deps, add config docs

pisa/stages/utils/pi_kde.py
Added a basic KDE stage. Tested with DRAGON datarelease sample.
- This doe not yet contain any support for uncertainties - something we'll need to think about.
- GPU support does not work, as pycuda (what KDE uses) wants exclusive control of the GPU.
- It is _very_ slow for the full neutrino sample, but I guess using this for muons should be fine
=> Pi kde support

pisa/core/binning.py, pisa/utils/jsons.py, pisa/utils/matrix.py
Should fix issue #570 .
It was possible in `binning` to give an index that is actually invalid. This would cause an obscure error later on when only the length of the now string index is checked. Even more obscure, if the given index string happened to have the same length as the binning has dimensions ("pid"), it would pass the length check and break later with an even more obscure error. 
Let's raise an exception instead with a helpful list of the keys that would have been valid.
=> Fix matrix unit test and make small fix to binning

pisa/utils/vectorizer.py
* `min_count` arg to `replace_where_counts_gt` is converted via `FTYPE` (and fix signature of `replace_where_counts_gt_gufunc` from `i4` to `f'{FX}'` 
* bugfix: arg order passed to `replace_where_counts_gt_gufunc` was incorrect
=> Bugfix: order of args to replace_where_counts_gt_gufunc was incorrect

pisa/core/map.py
The current implementation of the `poisson` fluctuation method cannot be used to fluctuate MC events in a meaningful way. Furthermore, the fluctuation does not have the standard deviation that is stored in the Map, and instead fudges the standard deviation in a way the user might not expect. 
This PR implements the Scaled Poisson Process derived in [Bohm & Zech 2018](https://arxiv.org/abs/1309.1287) and applies it when the stored standard deviations in a map are not sqrt(N). This process ensures that the mean and standard deviation are correctly observed and is a reasonable approximation from the fluctuation that can be expected from a Compound Poisson Process that produces our MC expectations. 
If a map has errors of sqrt(N), as is the case after `set_poisson_errors()` has been called, …
=> Scaled poisson fluctuation

pisa/core/distribution_maker.py
This is a simple fix on the `get_outputs` function of distribution maker, in the case where we want to return the sum of all maps. 
previous behavior (using the python `reduce`) didn't work once you added a third pipeline, because the sum of two MapSet is a Map, and not a MapSet.
=> fix the distribution_maker get_outputs function to properly handle more than 2 pipelines

pisa/stages/absorption/pi_earth_absorption.py
This PR addresses issue #596 . The unsupported functions `np.dot` and `np.exp` are replaced so that both 'cpu' and 'gpu' targets work with this stage. I checked that both import without errors and give the same result.
=> Make earth absorption stage compatible with GPU target

pisa/utils/config_parser.py
Attempt to fix issue #608 :
If `[^a-z]units\.[a-z]+` regex is found in a value being parsed, try to parse as a Pint quantity (possibly with errors via uncertainties). If that fails, or if that string wasn't found, parse as a literal value (i.e., NOT as a Pint quantity).
=> Attempt to fix issue #608,  parsing non-param args in sensible way

pisa/stages/utils/pi_kfold.py
This stage splits the data into k-folds using the `KFold` class from `scikit-learn`. It then selects the "test" indices from one of the folds and sets the weights of all other events to zero. This allows one to run a pipeline with one part of an MC set and fit it back with another. Optionally, weights can be multiplied by the number of splits to normalize the final rates.
=> add kfold splitting stage

pisa/core/binning.py
Work started in PR #612 by @atrettin, hopefully this fully fleshes out that idea. Please test from my branch, @atrettin & provide any feedback.
Note that the big change here is to make `is_lin` and `is_log` describe binning behavior, and not anything to do with whether or not the binning is "regular" in linear- or log-space. There is an additional property of `OneDimBinning` called `is_irregular` which will test the regularity of the binning in the space in which it is defined, if that information is useful / necessary (this is used, in part, in the new `__str__` method to allow for more concise string representation of binnings; also could be useful for optimizing certain functions on the bin edges).
* `is_lin` and `is_log` no longer imply uniformity in linear-/log-space
* still can use …
=> `OneDimBinning`: `is_lin`, `is_log` describe binning behavior, NOT regularity in either space

pisa/stages/utils/pi_set_variance.py
This stage allows one to set relative variances on histograms produced by the KDE stage manually. The variance in each bin is simply proportional to the total weight in the bin and inversely proportional to the number of MC events, but the factor of proportionality has to be set manually. This scaling gets at least the most basic proportionality of the variances on KDE estimates right, as referenced at the bottom of page 7 [of this lecture](http://faculty.washington.edu/yenchic/18W_425/Lec6_hist_KDE.pdf).
=> Stage to set variances after KDE

pisa/core/param.py
Does what it says on the tin: You can now delete items from a ParamSet. Comes with unit tests to make sure it works as advertised.
=> enable deletion of Param from ParamSet

pisa/core/translation.py, pisa/stages/utils/pi_adhoc_sys.py
One more test to run is to check for those variables in which we see disagreement after the fit, how much our fit would be influenced if we had some systematic to account for it. 
This stage simply rescales all events by the ratio of data/MC in the same binning that was used to make our data/MC comparisons. Those ratios are produced externally and stored to a JSON that is loaded by the new stage. The JSON should simply be a dictionary, where the keys are the variables to be checked and for each key it contains the binning and the data/MC ratios. Our verification sample data/MC comparison script produces these: 
https://github.com/IceCubeOpenSource/fridge/blob/master/analysis/oscnext_verification_sample/post_blind_fit/post_fit_data_mc.py
This also required implementing the 1D lookup …
=> Adhoc systematic for additional blind fit checks

pisa/analysis/analysis.py, pisa/stages/data/pi_simple_signal.py, pisa/stages/data/super_simple_pipeline.cfg, pisa/stages/likelihood/pi_generalized_llh_params.py, pisa/utils/stats.py, pisa_tests/likelihoods_1D_test.py
This PR corrects a major flaw in the way I originally set up my simple 1D likelihood test. 
Initially, the pipeline I created in pi_simple_signal would generate, at every iteration of the minimizer, a completely new distribution of weights that were randomly distributed according to a gaussian signal. This meant that the actual locations of the weight within the analysis binning varied from iteration to iteration, which is not exactly what I intended to do.
Instead of doing the above, a single distribution of weights is now generated only once, at the setup phase of the stage. These weights are distributed uniformly over the chosen range of parameter values, and during a fit, a gaussian PDF is used to _re-weight_ the already generated weights. This is closer to the scenario we have in …
=> correcting flaws in the likelihood test script

pisa/core/translation.py, pisa/stages/osc/layers.py, pisa/stages/utils/pi_adhoc_sys.py
Looking a bit more closely into this stage, I noticed that path lengths seem to be calculated in a way that is not very straightforward to understand. This PR tries to simplify the computations made in layers.py to make them easier to understand. I also added a few assert statements to prevent one from defining unphysical detector locations and radii definitions.
Note that the only thing that has changed computationaly is the way the full path length, as computed in extCalcLayers and calcPathLength. The logic and steps behind the multi layer calculations should probably also be looked at, though it will have to be in a later PR :)
=> Osc layers

pisa/core/param.py, pisa/utils/config_parser.py
Added the log-scaling option to the config parser and added a doc-string to the option.
=> Parse param config for log-scaling

pisa/utils/hypersurface/hyper_interpolator.py
In certain circumstances, stripped units can cause errors when serializing hypersurfaces. This PR fixes the problem and removes the `UnitStrippedWarning`.
=> Fix issue with  stripped units

INSTALL.md, setup.py
Old version gives `TypeError: expected dtype object, got 'numpy.dtype[float64]'` when I try to initialize an DistributionMaker
=> increase numba requirement

pisa/__init__.py, pisa/core/translation.py, pisa/stages/flux/mceq_barr_red.py, pisa/stages/osc/nusquids.py, pisa/stages/osc/prob3numba/numba_osc_hostfuncs.py, pisa/stages/osc/prob3numba/test_numba.py, pisa/utils/numba_tools.py
This PR allows one to set the number of threads to be used for multithreading with one central environment variable `PISA_NUM_THREADS`. This variable is used by `numba` as well as any "custom" multithreading implementation (of which there is currently only one, for fast histograms). 
Multithreading can be made much more simple than we used to: All one needs to do is to implement things with simple for-loops and then use numba's `prange` instead of `range` in for-loops that can be naively parallelized. This is done for the `mceq_barr_red` stage as well as the fast lookup procedures. I would recommend going this route as well for `prob3`, but I don't think that I'm going to do this because I'm not using it myself. I had to remove the `target` keyword in some places because it no longer …
=> Set number of threads globally with PISA_NUM_THREADS variable

pisa/stages/flux/mceq_barr.py
I modified the full barr stage to use for-loops, which gives a small speedup. When running the full oscnext high stats neutrino pipeline it improves from ~12.3 s to ~8.2 s. The (very simple) notebook for that is [here](https://github.com/icecube/wg-oscillations-fridge/tree/master/analysis/sandbox/lfischer/test_barr_stage).
There are some additional modifications similar to the changes in the reduced barr stage.
* updated docstring
* moved antipion_production function into stage
* linked containers for speedup
* added check for completeness of spline file
* converted barr parameters application into for loops
=> Modified mceq barr stage to use for-loops.

pisa/__init__.py, pisa/stages/osc/nusquids.py, pisa/utils/numba_tools.py
Because the nuSQuIDS stage didn't check whether the `TARGET` was `parallel`, it would use multicore despite the target being CPU. We now check whether the target is `parallel` and _in addition_ make sure that the global variable `PISA_NUM_THREADS` is always 1 if `TARGET` is `cpu`.
We also only give out the warning if the user tried to set `PISA_NUM_THREADS` in their environment explicitly larger than 1, but the `TARGET` is `cpu`.
=> Multithreading fix

pisa/analysis/analysis.py, pisa/core/param.py
Just two small fixes: 
* Setting `reset_free` when doing a constrained fit should only reset just before the fit starts, but not on each iteration when the penalty is doubled. Otherwise, the entire fit would have to run again just because it ended up in a region that is not allowed, which would take a long time. 
* The `Param` class should not make up its own TeX name when it is set to `None`. Especially in this case, the TeX code was broken every time the name of the parameter had two underscores inside. Our plotting scripts check if the TeX property is None and if so, take the name string instead of the tex string.
=> Small fixes to analysis and param

pisa/analysis/analysis.py, setup.py
With this PR I add a new option to the box of algorithms available in PISA that allows the user to use any of the global (https://nlopt.readthedocs.io/en/latest/NLopt_Algorithms/#global-optimization) and local (https://nlopt.readthedocs.io/en/latest/NLopt_Algorithms/#local-derivative-free-optimization) algorithms. The reason why I only chose to support the gradient free methods is that NLOPT doesn't apply a finite-difference method automatically and expects every function to supply its gradient itself. Most gradient based algorithms are also included in scipy anyway and for our purposes the gradient-free methods and global searches are more interesting. 
NLOPT can be dropped in place of scipy and iminuit by writing a dictionary with `"method": "nlopt"` and choosing the algorithm by its …
=> Support all gradient-free algorithms from NLOPT

pisa/core/distribution_maker.py, pisa/core/param.py, pisa/core/pipeline.py, pisa/stages/README.md
Before, only the current representation of the selectable params would get overwritten in the distributionmaker instantiation, such that params of the same name would point to the same object.
Furthermore, the update function in the pipeline would call update on the params instead of the selector.
Also, the update in param selector would ignore the values in the underlying dict
=> Correct handling of selectable params

pisa/analysis/analysis.py, pisa/core/map.py, pisa_examples/resources/settings/pipeline/fast_example.cfg, setup.py
Add a module to perform a staged fit, where a later fit starts from the best fit point of an earlier fit. 
The use case for this is primarily to polish the result of a global search. For example, I can run NLOPT's CRS2 global search algorithm for up to 30h and then polish the best fit point using L-BFGS-B with the following kwargs to `fit_recursively()`:
```
method="staged",
method_kwargs=None,
local_fit_kwargs=[
fit_nlopt_crs2,
local_fit_scipy,
]
```
where
```
fit_nlopt_crs2 = collections.OrderedDict(
method="nlopt",
method_kwargs={
"algorithm": "NLOPT_GN_CRS2_LM",
"ftol_rel": 1e-7,
"ftol_abs": 1e-5,
"maxtime": 30 * 3600,
},
local_fit_kwargs=None,
)
```
and 
```
scipy_settings_l_bfgs_b = {
"method": {
"value": "L-BFGS-B",
"desc": "The string to pass to scipy.optimize.minimize so it knows …
```
=> Add staged fit

pisa/core/param.py
In some special pathological cases, rounding errors can cause a rescaled value to end up outside the bounds of a parameter. In this case, we want to clip the value back to the edge of the range.
Another small issue is that some functions rely on the fact that `range[0]` is the smaller value and `range[1]` is the larger value. Because this is a thing that many users might rely on elsewhere, we can avoid hard-to-catch numerical errors by enforcing that order in the setter method of the range.
=> Fix small parameter scaling issues

pisa/stages/aeff/weight.py, pisa/stages/utils/hist.py, pisa/stages/utils/kde.py, pisa/utils/hypersurface/hyper_interpolator.py, pisa/utils/hypersurface/hypersurface.py, pisa/utils/hypersurface/hypersurface_plotting.py, pisa/utils/kde_hist.py
This PR adds the option to estimate errors on KDE'd histograms using the ``bootstrap_kde`` class from the KDE module that we already used. It's of course very slow and not recommended to be used in a fit, but it is very useful for fitting hyper surfaces with statistically sound errors. Other changes are:
* To the ``aeff.weight`` stage:
* Scale errors along with weights in the ``aeff.weight`` stage
* This makes it possible to do the weighting _after_ making histograms in a pipeline. In this way, KDE histograms have to be calculated only once before a fit starts, and the histograms are simply scaled with the efficiency.
* to the ``utils.kde`` stage:
* Add option to stash histograms in the KDE stage. Ties into the point above: the (expensive) KDEs only need to be done once before a fit.
* …
=> Implement KDE bootstrapped error estimates and more

pisa/analysis/analysis.py, pisa/stages/utils/bootstrap.py, pisa/utils/config_parser.py
This PR adds a bootstrap sampling stage that can be used to estimate MC uncertainties, and a few smaller fixes:
* If a string was given for metric in the Analysis, it is now converted into a list of one string. All other functions in the class assume that `metric` is a list.
* Add `scales_as_log` to the list of parameter attributes. Otherwise, putting it into the configuration is interpreted as a new parameter called `scales_as_log`.
The `bootstrap` stage creates a bootstrap sample of the entire input data sample, i.e. it randomly draws samples with replacement until the bootstrap sample has the same size as the original sample. Instead of manhandling the entire arrays, though, it adds equivalent weights to the samples, i.e. a sample that was selected twice gets a weight of 2, and so on. …
=> Add Bootstrap sampling stage and some small fixes

pisa/stages/utils/kde.py, pisa_tests/test_command_lines.sh, pisa_tests/test_kde_stage.py
This PR makes the KDE bootstrapping that we use to estimate MC errors on KDE'd histograms reproducible. Since the `kde` module didn't support setting seeds, I had to "in-source" the bootstrapping into the KDE stage itself to do this. I also added unit tests to ensure that the histograms with errors will give the same result with the same seed and different results with different seeds.
=> Make KDE bootstrap reproducible

.github/workflows/pythonpackage.yml, pisa/core/translation.py
Make PISA compatible with Python 3.10. Hopefully this will not be too painful.
=> Compatibility with Python 3.10

.github/workflows/pythonpackage.yml, pisa/core/binning.py, setup.py
The `assert_compat` method was missing from the OneDimBinning class, and therefore the `assert_compat` method from the MultiDimBinning class would fail with an obscure error. This PR fixes this behavior and adds a unit test to ensure that the appropriate error is raised.
=> Add missing method to assert compatibility

pisa/analysis/analysis.py, pisa/core/pipeline.py
This PR greatly improves the support for externally defined custom PISA stages and custom fit methods. 
Concerning fit methods, it turns out that I had designed the `BasicAnalysis` class in a dumb way, I could have done it far easier with the `getattr` method instead of writing my own dictionary. It is now possible to easily implement custom fit methods in a sub-class, all they have to do is to follow the `_fit_{method}` naming scheme. This is also tested in a unit test. 
The only change for analyzers is that `fit_ranges` has been renamed to `ranges` and `fit_octants` has been renamed to `octants` for consistency.
For externally defined stages, PISA will now search for stage definitions in the `{stage_name}.{service_name}` module if it fails to find a stage in …
=> Improve support for custom stages and fit methods

pisa/stages/reco/simple_param.py, pisa/utils/hypersurface/hyper_interpolator.py, pisa/utils/hypersurface/hypersurface.py
Importing abstract base classes collections.abc instead of collections. Should be compatible with Python 3.10.
=> Import abstract base classes (collections.abc)

pisa/utils/kde_hist.py, pisa_tests/test_kde_stage.py
This PR adds unit testing for the "stashing" feature of the KDE to ensure that scaling stashed histograms with a subsequent weighting stage is strictly equivalent to scaling the weights first before applying the KDE. The behavior of errors is tested with both bootstrapped errors and errors set ad-hoc with the `set_variance` stage (the latter is aimed at backward compatibility with the verification sample). 
The KDE unit test also uses a much faster testing pipeline now, reducing the runtime for this unit test from 20 s to ~1 s. 
One further small tidbit is that I tracked down the origin of the `UnitStrippedWarning` one always gets when running the KDE stage and fixed the offending line. This has annoyed me for a long time.
=> Better KDE unit tests

pisa/analysis/analysis.py, pisa/utils/stats.py, pisa_tests/run_unit_tests.py, setup.py
In octant fitting, if parameter values are not reset free between the single fits, the intended behavior is that after fitting the first octant, the parameter values (except for theta_23) are reset to where the first fit started. Due to the missing deepcopy, instead, they were set to the end point of the first fit instead.
=> fix resetting parameter values for 2. octant fit

.gitignore, pisa/__init__.py
Just a small change that allows PISA to run on platforms other than Linux x86_64.
Somehow, there is this alias, `complex256`, that only exists on x86_64 for `clongdouble`. No idea why that would be, the workaround is also very simply to set the alias manually.
https://numpy.org/devdocs/reference/arrays.scalars.html#numpy.clongdouble
Oh, and I always get annoyed a little by this automatically generated file being shown as untracked in git, so I added that to `.gitignore`.
=> Clongdouble alias

pisa/core/distribution_maker.py, pisa/core/param.py, pisa/core/pipeline.py, pisa/utils/callable.py, pisa_tests/test_covariance.py
Basic functionality is here - hoping to continue work on this on a branch in the IceCube PISA repo rather than my personal fork. 
What's here, now
- Adding covariance matrices to do fits with correlated nuisance parameters 
- Code to write and read functions to and from json files 
What's not yet fully there 
- Creating `DerivedParam`s and defining functions in config files 
- Serialization of the full state, including `DerivedParam`s
=> Adding Covariance Matrices

pisa/core/detectors.py
Otherwise will create an import loop, which is very inconvenient.
=> move an import which is only used by the unit test into the test function itself

pisa/analysis/analysis.py
When the `_fit_scipy` function is called with a `list` of `MapSets`, it will still try to call `data_dist.allclose(hypo_asimov_dist)`, which fails since `data_dist` is a list. This is fixed by checking if this is a list first, and if so it will then check if all the mapsets are close instead.
=> fixed small bug in `fit_scipy`

.github/workflows/pythonpackage.yml
We don't support python 3.7 anymore so let's bump the python version for the github workflos.
=> Bump python version

pisa/core/param.py, pisa_tests/test_covariance.py, setup.py
I deprecated some prior functions that just call other functions. In case of the ParamSet they will even yield wrong results since they don't know about the deamon flux stuff
=> Deprecate duplicated prior functions

pisa/core/pipeline.py, pisa/core/stage.py, pisa/stages/README.md, pisa_examples/pisa_modes.ipynb
A few small things that I encountered while trying to get up to speed with core functionality:
* pipeline.py main script docstring adapted (broken, needs to be fixed or removed)
* stage base class: docstring updated
* no cake vs. pi distinction anymore, right? ("pisa pi" still mentioned in a few other places, but meaning not necessarily clear to a newcomer)
* lacking effect of promised effect of debug_mode as far as I can tell
* missing parameters error_method and profile, and other superficial things
* also cleaned up some left-over references to removed objects in comments
* updated table of directory contents in stages/README.MD (and added expected_params to list of std_kwargs)
* given the importance of the concept, expanded introductory text on pisa (stage) modes in …
=> Stage and pipeline related documentation touch ups

pisa/utils/plotter.py
At least in matplotlib 3.8.4, `plt.subplot` doesn't accept a float for the number of rows/columns, only an integer. This leads to exceptions when trying to run scripts `distribution_maker.py`, `kde_hist.py`, etc. with plotting activated. I believe only the unit test for `kde_hist.py` could have caught this, but it fails due to the missing (but accepted) pycuda dependency already.
It doesn't seem worth checking whether previous versions of matplotlib were more lenient, because passing an integer is surely backwards compatible, isn't it? I've also removed the very old TODO in the line above because there is an automatic row/column setup...
=> fix plotting 2d arrays (not caught by unit tests)

pisa/stages/data/simple_signal.py, pisa/stages/data/super_simple_pipeline.cfg, pisa/stages/likelihood/generalized_llh_params.py
* seems these were forgotten when `Container` methods were changed
* also make "super simple" pipeline config work again (kept here for now; something like this should probably be integrated into examples eventually instead)
* closes #784
=> Apply obvious outstanding fixes to `simple_signal` and `generalized_llh_params` services

pisa/utils/config_parser.py
Our possibly best documentation of the expected pipeline configuration format is the module's docstring, which contains several small mistakes and is outdated or incomplete in several places (see https://icecube.github.io/pisa/pisa.utils.html#module-pisa.utils.config_parser).
There also seems to be the same small bug in two methods of `PISAConfigParser`:
* I could not find out whether the `_validate_value_types` method of `RawConfigParser` ever returned something. At the time the code was introduced, https://github.com/icecube/pisa/blob/master/pisa/utils/config_parser.py#L1184 suggests it was based on https://pypi.org/project/configparser/3.5.0/.
* In all recent versions (for example, https://github.com/python/cpython/blob/3.10/Lib/configparser.py#L1171), `_validate_value_types` does not …
=> Apply small fixes to (mostly) docstrings of `config_parser` module and extend unit test

pisa/general_conventions.md, pisa/utils/config_parser.py
Also note that the guide now states that "there are no general conventions on how to test a service currently in place" instead of referring to the non-existent "`pisa.core.pipeline.stage_test()` function" (see https://github.com/icecube/pisa/issues/795)
=> Fix broken links in general conventions guide

pisa/stages/aeff/param.py
Bringing back the parameterized effective area stage that.
=> Revive parametric Aeff stage

README.md, pisa/general_conventions.md
In the absence of a dedicated [contributing guide](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors), at least add link to conventions (which includes some information typically found in a _CONTRIBUTING_ file) to readme in root directory.
=> Add link to general PISA conventions in root readme

INSTALL.md
Main changes:
* update and move quick start instructions back to top
* default method suggests using Miniforge (with either conda or mamba as package manager) instead of Anaconda or Miniconda with conda (see e.g. https://www.rc.virginia.edu/2024/10/transition-from-anaconda-to-miniforge-october-15-2024/, https://www.anaconda.com/blog/update-on-anacondas-terms-of-service-for-academia-and-research, https://docs.anaconda.com/anaconda-anon-usage/)
* restructure such that it becomes more apparent which steps are universal; in particular, only clone PISA after setting up environment, so that git may be obtained from conda-forge in the case of installation using the Miniforge distribution
* clean up notes on dependencies
* remove instructions on how to interface with fridge or specific paths on …
=> Restructure and update installation instructions

INSTALL.md, README.md
The installation file is very large and a bit confusing. We need to clean up a little. I started by clarifying the difference between the two presented methods and expanding the anaconda version.
=> Update install instructions

pisa/analysis/analysis.py, pisa_examples/resources/settings/minimizer/de_2nd_octant_popsize_10_init_sobol_polish_tol1e-1_maxiter1000.json
* also (re)introduce support for a few more scipy minimisers
* redefine `_minimizer_callback` signature to support "trust-constr" minimiser
* add a few quick minimiser tests (with and without constraints)
* minor touchups
=> Enable (in)equality constraints for use with local and global scipy minimizers

pisa/stages/discr_sys/README.md
The previous version described the use of scripts that aren't part of pisa. This change therefore:
* removes the pisa unrelated descriptions
* updates the use instructions with specific config and pipeline example
=> Update discrete systematic README (Ultrasurface use)

.github/workflows/documentation.yml, .github/workflows/pythonpackage.yml, .github/workflows/release.yml
Testing whether we can remove the cap from the workflow also.
- python 3.10 workflow: a recent pip install (25.1.1.) is available already on the host.
- python 3.8 workflow: pip 25.0.1. is simultaneously installed.
As expected, this runs through successfully. If we merge this PR, the pip version with which PISA is installed will not be frozen any longer. This might serve as a convenient monitoring tool and provide an incentive to modernise the setup procedure eventually.
Edit: also took the opportunity to update the other two workflows (we will only know whether they work when pushed to master (documentation.yml) respectively a new release is created (release.yml)).
=> Remove cap and explicit pip install from workflow

pisa/stages/discr_sys/ultrasurfaces.py
apply gradient-lookup indices only to appropriate event grouping and record all gradients (not just for last parameter for simplicity) when in debug mode
=> Fix ultrasurfaces in event-grouping mode and improve debug output
